apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-cloudflare-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgB4i4dRrQZBxzl2OKcdqt0FpPAhuw6qOFWhqVvwhJvYI7x5Olc4jEo0/jGGWST3lBdgFbiNO6vOPh5W2Gja91lYIkAY/UHuQ0C7BESR01taUt75pPxynLbkcjYr430+B63KVhn2j5Gw+aTZRjxmHn+y1pyCjHccJFGvo0tx9UIbE2AfaG0cTbPm9iPWKBsJPrraVnQnZWrmUuo0vv4nz4JoXYxAKIqjNlW8BAyBvmNh9QvMiPAoEzXz4PcJMOrDpqPzlBokYK+p3DQ3E2RcG7IHP9MlrbyyIUSVIIbEtXwB+izL7FLsg0Oz9AZwUUlmmBU/f+AirMdUARwomZnbZhuwr+5KJeG+0FHWzSOL7veiW487E+3J5Pf7iPcH1JTlMVxo4t8iXZukvQk9bN8twSDZY8ADv+sT1bC4pJcjgaDB1k3kTuj/6iJP1U2+rrSW2/qLMxMdRSocjl+/Osizb9vhBDY/8AvBwK8kS6CKIknWKmB3lgnRTbHLugNeg5n7HsnGlqpN6WNbf85r+CIHEVabjpC4VajX1XKSDpUL2kflCt8+e0ejUkzVgTMBhBf0VnWcfm3Z1l3+XBmDRwGVEwsFexp9lBwdeuCgd5YX4fHE4udIkupwF8ouYGEJ8HPxKr+hZAe98WjfvfFL7c9M02HaXLItBa8+GCDn3W2HFJ1W98kbUxvcqkICZk2yNvXyK5tHYITyEIKP4gBFDZbg8EAmxhsk/Q7N4LUiaeSPy4r7H/af9g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-cloudflare-turnstile-secret
      namespace: standalone

