apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAjAh1RPhe0Q4mpJar1Bqyt4h0eWQEn4jHuhPI/ORioQhnneFvHViyaUkYUb/JN76q+9lboZ3bDzPlwTNBoKgFkU3PhAdINRSHn33ZYxIPVJIdBZkbqeUVwKHu6jx2SENW7bkY8DL++H7w8RPWT/L2ivVu/CikZe4JWZntaVzYItZuI7SqdPwwPX2yTOuvUYJu2FZaOUURz7v+q1JKNQCsaKHDyw0XMmeAkoSfJeIi76Mx4F9wO6YzgrpFsZTrW7R0mfpdu9ZI+xR+AGZ86CwrHAZqK+5Dqn3m3W15fmESEux6Tj0nKepj3xypHaG9cQHJFtLucMKx2UboJ6ePoCrpOrrKYnkaWBJKvjXiobypgffdKJ+ZPFYr6nnNh1GRhd4qS6T6wxsD1cpsryp8o0pZh6BgqItMRoT1DJfpW1mr3OIDUynH6/CFA8sKjh22Wfl6KJ9hiBTfKA3USLcvqOioh7UBfTQMX6/IYiow/KYavWA69dbzaweDuId5EKcHhNFKzh57Fd1bjCCJcWhR7qcLKFNUxPglD8sdRqfFsq3J8xsu4yBZijZ3UT23uUe5yH74IAp62JNACETfQ0Pcyr8Ndadrpj9eAntI2x/SPZcTrETSpVNZ2b6jn0oXPhOaTO7i6ghLe2PVinp1llOkCziXEPVidib4YRK3l87MgCITeiSIxUf5+gZedfuazNDeP+MZ0Gt0kNz1/6mSTO/j/KO0PLnA80e643L+T
    POSTGRES_PASSWORD: AgAREZTokME9zln0id4vcYGreL8F/BXWujdss9/jl5vwi7AWFpoU5EjfEHpELC3efMllsJB32bSLKznSCDIMJdC05xBaNZGVXrYyo8zwmW28e/AU+NHTcTNhQn0gpt8Jj/ygrN2Cg5j5f2D7y52lxZXIFsUmfJSSdxX/orAzPwDpxT6JYwXazP0q+xdQnevxDUmcByI6BXjW16RjSS9s3AGX/CY7QtYgGzlkrMSV+NghH8Fv9TLtAj3QbNcDr95QLPA0JEqpgooLm6aIsc3Ey34XOtdVg6ZnlampZRDHb41zj/iGd3IJb1LHM5MAB8SG635dRqbap8upe05Kd9soiaHScKmRi+q6rGt7xibaQxSIm4GtEUGtqd/s85kwVbVYts9qgVacdl4W5tT/YnfM/CjPFd39hr6ugPh3pDGte7rsJKC9E9+Ea9I0kQcvOPK5EdmfTM4W+qSYcHiNLdzRcXgw/YC59yV3O81Fg0QKianN0o9GQj2tl06PWbQVQ8CAWv0SfL3hVbLD68T2xOQl7Ej1pKSAQ2aP89nMq/q4kvibcXeCfxzvK4byDhp6skblM3qfD2IsFLADNCBXqPchxkvcDSQJgxXAqETVj66qzm6Szufspf2VXXDrz9D58IOwoLsNVqTSQ+QpbKzFnvQZkv9Jmgn1hok372flbVuoxnFoBq/H5unk7YI2bAQMguVFaF+B3Ak53SV4JdDEsoZXbqMzgMGxIHblunVK
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-database-secret
      namespace: standalone

