apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgDBzG0cIUypiws1f2ybbiAjkCK6oXDzeoCvfDTwEq9HPgLN34pcMl8+9KIum8kPRd9KakpTb8049s2bOoDGfL6B74so7rZ1iKe5d1bc+kT1X39k+67tQpENs2qUP7rd/QvsQa/hgs9neaCs++Qau3vsUE+yRsbN0F+UGQ25biusj3YIyvZUM+bx611SOgeg2hT5Ky0fB5qKNjPDppdKnBBQ0FinBCd5Rt7WvqkTiaEPuKk7haeWmCb1p6etufeUKqK1m/whuHQRfEQmmn24p4C1x+NGAT5EADOVzOpaGeLESjK+FvwOrvFwe4P4Pou/H0s5LBRu6gigS7w25UyQ7OYssa9j2KQtoe42+0vLBRQjdBjkisicF5YiF50oHrZWyopXVSTaP/EBDfj5BSQPFh8LKG4ZammnXv3VaNWiPp1BXh29w29ICvQY5ZTNX438U6ArzyGsGV83OT20CR9+lOFKEI+bM45fMUtSVYSMuAF1V7dX0hSOsTnF2QZCTsd3fKrWCaguKcbaqBZXR1cW7BXKQZUhObMGt7I5ERuHuf9YOWQqkR69rs5bw0f+9ZNQ26+dp6b2zMWddtbcKKwiRHqXaI/f72jRQws4T70ATOZlzMz0LEFVnaE3XbWjCGnGMNHfBv7eW61tLC6ZEQG13DXqULX/Ptbetyyi9/HIkyvCUDqp3iuTETuZTEY8ODw+F/ESKLb31OjU748ZBt6BrEWh2dQlYifP+ioK1uDqjIKb
    POSTGRES_PASSWORD: AgCFWuJkzzVDcWYuky54x180z/p78nLeg2dSB0Je34h7l/WS6qbzdPSHz0mCv3fyna5tztGxxtqqD+MrZDZ8cgYz73CZz15x0ei0Em9ypv9/vnwgm/qQE3OoMZe1W5/OCXFb0RUE3GI7iiCvU4DDnC50Ynr5nnnhjvoRpGcyaVxQyzD3FWzWXFm1kkKHd4SWx5icxHKAkOZw280W1nHzMx+/MrIhNtgXDab9wGthWANhUxmkrkvHCDCXP35230KwsNYgQSa6B2z3LnMQ0XzBNWyeISg/nwcKjNT22fajfWxDuoPQ4XJ3pnDeFz0KVIXN7FjUtzae8L20kJaDgdTw6gpeI5J4ca6jMqbV5tG642QULzLNHN4AZU6z2cTIbgUPdxNYMl5gyeG8KH3coIYa7qL51hVHpdRhiGpnH2juTIh9omqGwnrqSd7wW6rveA6NgCD2f4CrT4wi5iQYQEm5+LZh+eNBNsKHXVuCOqbTvWlM6JtI/j/Ao+Pven5fLRD0hbByHZ3npp0VMgkxQlBPRsDoEU7O0k0NvANAaM9chVWqVD3hrGxQd533PD5Z3TQfzIu4BFDV3O/k7F/9HowvmozPUxtExv0/TlAgXCi9NIhmddtKXjhPoHcLx+i2t8l8G+2g9LkmhuZhywYskohb6QIjFLOhyIQnMOxryFDk/tTkYFXryZUmJDjKAvx3SZIGrCnqYlYTlQuizaiXP+L8YsQz38Ug4vYQ4b2GQro7gIBx
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-strapi-database-secret
      namespace: standalone

