apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: marianum-next-cloudflare-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgB9Tdgrb/2F3nj9VJLbKoIx4RKeK4lhWuVBkrHsF3a9DWfIVIMS7uHg6hzG705fqzWZR+4K+mxOJ2noUva6g7fTQ/eGPZurhCS8Bb5uWOskKpFyZXYIVS9XvigTyiirKUT+MG0wmdDmFzVZQCIy/By65FU+Wmj24bWZmWMkrQlAF0znLbt/QOr7Y4UvWnmABlODRFXnQ1CPu7yWOEnH18cRpW2n2bfgBBat7ToEOU0oqGVDBapHvoKkOC8YbIGRZSyk3kDGOzNWZj78ZjX3oZq/y7x1eJ6wWRjAujkHq81zY96TEcl3U59O/dAhOVpPmWjqEJ96znNyAEVkjCBn6zcIFs3H9xl6L8Qkwp0RCQQj1+2DQ9u5eK8Dn8sQ9EUJ+v08irDTB+jOGM75QFJv8v0OcyL3IcKFieEw9aHHg9HgAIFIXlHi0aqByJs4Ueb1k95WcHcmTRP6ZgDOZDsz89dCULrCvEhxhi7cqE5y66HF8cS1c9PBqr7pFfz/zUG8NFAH6Baub3W05UlfamURwHQDaiqaqVoYyJLLEg1vEF6GalvXB53Olz22Nug+/67sZfjRhYA4zyonHfuBGFTyiWKfZbA9Wy4cOMAIjlEOcy7FGS8a5wSytOHNayDu7wZzLZ1f7IcciZolgPHS2Mfrf3GlE8QqYAT3F4//OmnCv1cbjl14IlkByqVHDk6Ur+jG2OR4yrvzaNx+Ip0IS5IG5W1UjVK20XGnkTQt1hUrEw9n1ylL8A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: marianum-next-cloudflare-turnstile-secret
      namespace: standalone

