apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: marianum-next-cloudflare-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgC48qMu5I+1p5JRDGXVQVouUFaiSSmLGplWMfDpTuECtAQntr8eMtP77aBHZ2rB0FNhA5EZCNB7I9L3t/1VSrHkdsvhjza6/nldqCeYs5fVp5zJLYZpvPDp5qff8++hLZYJIafVGdhXCKGLbIQAiFNZvOqLZngB7vGkW/bI6Fe14j1r32t9bXTfgOrdbTm5wbilg5/KwUraGNAWteun6QmaXF5dWHPOE/c9hF9+MI6PkKpWFdr80k/a6LiGdOPCMJBitByPPxPFg7unk+VS8XAEClvmAgDUdxa4hD4YMzDt5lKXolpO2GVH9XcBoC94MxBYDbzV8IJIuloCF8+9EdAPaA4PCU0QvRXhkmhq/2YI4fC/uvnqVKIf3bXyror2N19JTknFP3sb5SDt5OlXlRS74CXIbh/dZAhDXPCNsomEwiHqrxtxHvEyaiIcJ/8oMU5fuT4AFHBwxPTs1Qp31uJJRIng8wQglUfy7uH1ux4wenn6FC0qm4S6Qz/va+a9gFy7CUwhYq/fv1kpzbmvWd8LWuXyXYHv7egX5pKFL1u+DfJQP07Col0HcYH+vsVSZWDtQzgiKiDdWsKxVjsrk//TecdeXVAsIfuUDJOI1NMldU4LkOYtx0Q9VUnzXwBi8foC8R8sH0kEb5o66ri0UeXx/jatTIMAlYSBITWUwOrtzGh7V8yshqnGQnt5VfhFVgL9GE18qUZ8pIR2sqnDnCng/RkqaPuRB0XMDvQwL7BP9RdhrQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: marianum-next-cloudflare-turnstile-secret
      namespace: standalone
